### PR TITLE
add the navbar and footer to the single page

### LINKED ISSUE #25: add the navbar and the footer to the [single news]
_task_

- create add the navbar to the single page [detail page ] 
- add the footer to the  single page [detail page ] 
- fix the style after adding the navbar and footer

### PR DESCRIPTION
**Pull request by mo7amedehab97**
add the footer and the navbar and give them style and fix the responsive for the footer relates #25

### CODE REVIEW

**Review by AhmedQeshta — COMMENTED** [review]
hi @mo7amedehab97 

## in the last section **Related Topics**, I suggest, decreasing margin-top to 0;
check it.

**this**
``CSS
@media (max-width: 375px)
.related-blog {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    margin: 50px 0 0 0;
}
``

**to** 

`@media (max-width: 375px)
.related-blog {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    margin: 0px 0 0 0;
}`

------------------------------------------------------------------
## another one, increase width card (Related Topics) like above cards to be same for all page

image

#25

**Comment by AhmedQeshta** [comment]
Hi @mo7amedehab97 

in card Related : 
image

### hint for help
`hr{
    background-color: #0000008f;
    border: none;
    height: 1px;
}
` 
#25

**Comment by AhmedQeshta** [comment]
Hi @mo7amedehab97 
@AhmedQeshta 

### Fix bug images In HTML 
by **removing `/` form source image**

- [x] Remove ` header image `  and add this `header image`
- [x] Remove ` Recommended for you `  and add this `Recommended for you`
- [x] Remove ` Based on Like `  and add this `Based on Like`

R #25

**Comment by mo7amedehab97** [comment]
I'm done

**Pull request merged**
